[package]
name = "leaderboard_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
gloo-net = "0.2"

[[bin]]
name = "leaderboard_frontend"
path = "src/main.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2